//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csla.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataPortalTestDatabaseConnectionString {
            get {
                // Use environment variable for cloud compatibility
                var envConnectionString = Environment.GetEnvironmentVariable("DATABASE_CONNECTION_STRING");
                if (!string.IsNullOrEmpty(envConnectionString))
                    return envConnectionString;

                // Fallback to configuration value for local testing
                var configValue = ((string)(this["DataPortalTestDatabaseConnectionString"]));
                if (!string.IsNullOrEmpty(configValue))
                    return configValue;

                // Default for local testing only
                return "Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\DataPortalTestDatabase.mdf;Integrated Security=True;User Instance=True";
            }
        }
    }
}
